config/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("demoapp.urls", namespace="demoapp")),
]

urlpatterns += debug_toolbar_urls()

demoapp/urls.py
from django.urls import path

from demoapp.views import HomePageView, LongRunningView


app_name = "demoapp"


urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("long-running/", LongRunningView.as_view(), name="long_running"),
]

users/urls.py
from django.urls import path

from users.views import LoginView, LogoutView, RegisterView


app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterView.as_view(), name="register"),
]

background_tasks/models.py
from django.db import models


# Create your models here.
class KV(models.Model):
    """Model definition for KV."""

    queue = models.CharField(max_length=255)
    key = models.CharField(max_length=255)
    value = models.BinaryField()
    is_result = models.BooleanField(default=False)

    class Meta:
        """Meta definition for KV."""

        verbose_name = "KV"
        verbose_name_plural = "KVs"
        constraints = [models.UniqueConstraint(fields=["queue", "key"], name="kv_queue_key")]


class Schedule(models.Model):
    """Model definition for Schedule."""

    queue = models.CharField(max_length=255)
    data = models.BinaryField()
    timestamp = models.DateTimeField()

    class Meta:
        """Meta definition for Schedule."""

        verbose_name = "Schedule"
        verbose_name_plural = "Schedules"
        indexes = [
            models.Index(
                fields=["queue", "timestamp"],
                name="schedule_queue_ts",
            ),
        ]


class Task(models.Model):
    """Model definition for Task."""

    queue = models.CharField(max_length=255)
    data = models.BinaryField()
    priority = models.FloatField(default=0.0)

    class Meta:
        """Meta definition for Task."""

        verbose_name = "Task"
        verbose_name_plural = "Tasks"
        indexes = [
            models.Index(
                models.F("priority").desc(),
                models.F("id").asc(),
                name="task_priority_id",
            ),
        ]

demoapp/models.py
from django.db import models


# Create your models here.
class LongRunningModel(models.Model):
    """Model definition for LongRunningModel."""

    data = models.CharField(max_length=255)
    requested_on = models.DateTimeField(editable=False)
    created_on = models.DateTimeField(editable=False, auto_now_add=True)

    class Meta:
        """Meta definition for LongRunningModel."""

        verbose_name = "LongRunningModel"
        verbose_name_plural = "LongRunningModels"

users/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractUser,
    Group as _DjangoGroup,
    Permission as _DjangoPermission,
    UserManager,
)

# Create your models here.


class User(AbstractUser):
    objects = UserManager()

    class Meta:
        db_table = "auth_user"


class Group(_DjangoGroup):
    class Meta:
        proxy = True


class Permission(_DjangoPermission):
    class Meta:
        proxy = True

core/forms.py
from django import forms
from django.template.loader import render_to_string


class BaseForm(forms.Form):
    def as_div(self):
        html = render_to_string("core/components/forms/as_div.html", {"form": self})
        return html

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            initial_class = field.widget.attrs.get("class", "")

            extra_class = " input w-full"

            has_error = field_name in self.errors

            is_checkbox = isinstance(field.widget, forms.CheckboxInput)
            is_radio = isinstance(field.widget, forms.RadioSelect)
            is_select = isinstance(field.widget, forms.Select)
            is_textarea = isinstance(field.widget, forms.Textarea)

            if has_error:
                extra_class += " input-error"

            if is_checkbox or is_radio:
                # remove w-full and input-error
                extra_class = extra_class.replace(" w-full", "")
                extra_class = extra_class.replace(" input-error", "")

            if is_checkbox:
                extra_class = extra_class.replace("input", "")
                if "checkbox" not in initial_class:
                    extra_class += " toggle"
            elif is_radio:
                extra_class = extra_class.replace("input", "radio")
            elif is_select:
                # select select-error
                extra_class = extra_class.replace("input", "select")
            elif is_textarea:
                # textarea textarea-error
                extra_class = extra_class.replace("input", "textarea")

            field.widget.attrs["class"] = initial_class + extra_class

demoapp/forms.py
from django import forms
from core.forms import BaseForm
from demoapp.models import LongRunningModel


class LongRunningModelForm(BaseForm, forms.ModelForm):
    class Meta:
        model = LongRunningModel
        fields = "__all__"

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from core.forms import BaseForm
from users.models import User


class LoginForm(BaseForm, AuthenticationForm):
    pass


class RegisterForm(BaseForm, UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2"]

demoapp/views.py
from datetime import UTC, datetime
from typing import Any
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import TemplateView, FormView
from demoapp.forms import LongRunningModelForm
from demoapp.models import LongRunningModel
from demoapp.tasks import task_create_long_running_model


# Create your views here.
class HomePageView(TemplateView):
    template_name = "demoapp/pages/homepage.html"


class LongRunningView(FormView):
    form_class = LongRunningModelForm
    template_name = "demoapp/pages/long_running.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        data = super().get_context_data(**kwargs)
        data["object_list"] = LongRunningModel.objects.all()
        return data

    def get_success_url(self) -> str:
        return reverse("demoapp:long_running")

    def form_valid(self, form: LongRunningModelForm) -> HttpResponse:
        model = task_create_long_running_model(form.cleaned_data["data"], datetime.now(UTC))
        return redirect(self.get_success_url())

users/views.py
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView as _DjangoLoginView, LogoutView as _DjangoLogoutView
from config import settings
from users.forms import LoginForm, RegisterForm

# Create your views here.


class LoginView(_DjangoLoginView):
    template_name = "users/pages/login.html"
    form_class = LoginForm


class LogoutView(_DjangoLogoutView):
    pass


class RegisterView(CreateView):
    template_name = "users/pages/register.html"
    form_class = RegisterForm
    success_url = settings.LOGIN_REDIRECT_URL

core/templates/core/components/forms/as_div.html
<div class="my-4">
    {# non-field errors #}
    {% if form.non_field_errors %}
        <ul class="text-error">
            {% for error in form.non_field_errors %}
                <li>
                    {{ error }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}

    {# form fields #}
    {% for field in form %}
        <fieldset class="fieldset">
            <label>
                <span class="fieldset-legend">{{ field.label }}</span>
                {{ field }}
            </label>
            <!-- help text -->
            {% if field.help_text %}
                <div class="label">
                    {{ field.help_text|safe }}
                </div>
            {% endif %}

            <!-- errors -->
            {% if field.errors %}
                <ul class="text-error">
                    {% for error in field.errors %}
                        <li>
                            {{ error }}
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </fieldset>
    {% endfor %}
</div>

core/templates/core/components/pagination.html
<div class="flex gap-4 items-center mt-4">
    <div class="flex-1">
        Showing {{ page.start_index }} - {{ page.end_index }} of {{ page.paginator.count }} {{ object_name }}
    </div>
    {% if page.has_other_pages %}
        <div class="join">
            {% for link in links %}
                {% if link.link %}
                    <a href="{{ link.link }}"
                       class="join-item btn
                              {% if link.active %}btn-active{% endif %}">{{ link.label }}</a>
                {% else %}
                    <span class="join-item btn btn-ghost pointer-events-none">{{ link.label }}</span>
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}
</div>

core/templates/core/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}
        Document Title
    {% endblock title %}</title>

{% load django_vite %}
{% vite_hmr_client %}
{% vite_asset '__assets__/js/main.ts' %}
</head>


<body>
    {% block body %}
    {% endblock body %} 
</body>
</html>

demoapp/templates/demoapp/layouts/base.html
{% extends 'core/layouts/base.html' %}

{% block body %}
    <main class="container mx-auto p-4">
        {% block main %}

        {% endblock main %}
    </main>
{% endblock body %}

demoapp/templates/demoapp/pages/homepage.html
{% extends 'demoapp/layouts/base.html' %}

{% block main %}
    <div class="prose">
        <h1>Homepage</h1>
    </div>

    {# links #}
    <div class="prose">
        <a href="{% url 'demoapp:long_running' %}">Long Running Task demo</a>
    </div>
{% endblock main %}

demoapp/templates/demoapp/pages/long_running.html
{% extends 'demoapp/layouts/base.html' %}

{% block main %}
    <div class="prose">
        <h1>Long Running</h1>
    </div>

    {# Create form #}
    <form action="{% url 'demoapp:long_running' %}"
          method="post"
          class="bg-base-200 p-4 mt-10">
        {% csrf_token %}
        {{ form.as_div }}
        <button type="submit" class="btn btn-primary">Create</button>
    </form>

    {# result table #}
    <div class="prose mt-10">
        <h2>Latest models</h2>
    </div>

    <div class="overflow-x-auto bg-base-200">
        <table class="table">
            <thead class="bg-base-300">
                <tr>
                    <th>ID</th>
                    <th>Requested On</th>
                    <th>Created On</th>
                    <th>Data</th>
                </tr>
            </thead>
            <tbody>
                {% for object in object_list %}
                    <tr>
                        <td>{{ object.id }}</td>
                        <td>{{ object.requested_on|date:"c" }}</td>
                        <td>{{ object.created_on|date:"c" }}</td>
                        <td>{{ object.data }}</td>
                    </tr>

                {% empty %}
                    <tr>
                        <td colspan="100" class="text-center">No models created yet</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock main %}

users/templates/users/layouts/guest.html
{% extends 'core/layouts/base.html' %}

{% block body %}
    <div class="min-h-screen flex flex-col items-center justify-center">
        <div class="card bg-base-200 shadow-lg w-md max-w-screen">
            <div class="card-body">
                <main>
                    {% block main %}
                    {% endblock main %}
                </main>
            </div>
        </div>
    </div>
{% endblock body %}

users/templates/users/pages/login.html
{% extends 'users/layouts/guest.html' %}

{% block main %}
    <div class="prose">
        <h1 class="text-center">
            Login
        </h1>
    </div>
    {# djlint:off #}
    <div class="divider"></div>
    {# djlint:on #}

    <form action="{% url 'users:login' %}" method="post">
        {% csrf_token %}

        {{ form.as_div }}

        <button type="submit" class="btn btn-primary w-full">
            Login
        </button>

        <div class="prose max-w-none">
            <p>
                Don't have an account? <a href="{% url 'users:register' %}">Register</a>
            </p>
        </div>
    </form>
{% endblock main %}

users/templates/users/pages/register.html
{% extends 'users/layouts/guest.html' %}

{% block main %}
    <div class="prose">
        <h1 class="text-center">
            Register
        </h1>
    </div>
    {# djlint:off #}
    <div class="divider"></div>
    {# djlint:on #}

    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}

        {{ form.as_div }}

        <button type="submit" class="btn btn-primary w-full">
            Register
        </button>

        <div class="prose max-w-none">
            <p>
                Already have an account? <a href="{% url 'users:login' %}">Login</a>
            </p>
        </div>
    </form>
{% endblock main %}